# Generated by Django 4.1.1 on 2022-09-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_remove_doctor_department_remove_patient_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='assignedDoctorName',
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='doctorName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
