# Generated by Django 4.1.1 on 2022-09-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_remove_patientdischargedetails_assigneddoctorname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='patient',
        ),
    ]
