# Generated by Django 4.1.1 on 2022-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_rename_user_doctor_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='Emergency Medicine Specialists', max_length=50),
        ),
    ]
