# Generated by Django 4.1.1 on 2022-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
