# Generated by Django 4.1.1 on 2022-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_alter_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='discharged',
            field=models.BooleanField(default=False),
        ),
    ]
