# Generated by Django 4.1.1 on 2022-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_patientdischargedetails_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharged',
            field=models.BooleanField(default=False),
        ),
    ]
