# Generated by Django 4.1.1 on 2022-09-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_remove_patientdischargedetails_discharged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='discharged',
        ),
    ]
