# Generated by Django 4.1.1 on 2022-09-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_remove_patient_discharged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctorName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
