# Generated by Django 4.1.1 on 2022-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_alter_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.PositiveIntegerField(null=True)),
                ('doctorid', models.PositiveIntegerField(null=True)),
                ('patientname', models.CharField(max_length=40, null=True)),
                ('doctorname', models.CharField(max_length=40, null=True)),
                ('disease', models.CharField(max_length=90, null=True)),
                ('prescribed_medicines', models.CharField(max_length=500, null=True)),
                ('admit', models.BooleanField(default=False)),
                ('discharge', models.BooleanField(default=False)),
            ],
        ),
    ]
