# Generated by Django 4.1.1 on 2022-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
