# Generated by Django 4.1.1 on 2022-09-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_appointment_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
