# Generated by Django 4.1.1 on 2022-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_alter_treatment_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patientid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
