# Generated by Django 4.1.1 on 2022-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_alter_treatment_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
