# Generated by Django 4.1.1 on 2022-09-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_remove_treatment_admit_remove_treatment_discharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='symptoms',
            new_name='disease',
        ),
    ]
