# Generated by Django 4.1.1 on 2022-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_rename_symptoms_patientdischargedetails_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='doctorId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
